export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        "ui-slate": "#475569",
        "secondary": "#5c5f61",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#390c00",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#ffe9e3",
        "inverse-on-surface": "#f0effd",
        "inverse-surface": "#2e303a",
        "primary-fixed": "#dde1ff",
        "surface-container": "#ededfa",
        "on-primary-fixed-variant": "#0035be",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f2ff",
        "surface-bright": "#fbf8ff",
        "primary": "#003fdd",
        "error": "#ba1a1a",
        "outline-variant": "#c4c5d9",
        "on-background": "#191b24",
        "on-tertiary-fixed-variant": "#832600",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#444749",
        "surface-variant": "#e2e1ef",
        "on-primary-fixed": "#001356",
        "primary-container": "#2b59ff",
        "on-primary-container": "#ecedff",
        "tertiary-container": "#c23d00",
        "surface-container-high": "#e7e7f4",
        "on-secondary-container": "#626567",
        "on-surface": "#191b24",
        "tertiary-fixed-dim": "#ffb59d",
        "terminal-black": "#0F172A",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "secondary-fixed": "#e0e3e5",
        "surface": "#fbf8ff",
        "secondary-container": "#e0e3e5",
        "surface-dim": "#d9d9e6",
        "inverse-primary": "#b9c3ff",
        "outline": "#747688",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b9c3ff",
        "on-surface-variant": "#434656",
        "surface-container-highest": "#e2e1ef",
        "background": "#fbf8ff",
        "tertiary": "#982e00",
        "surface-tint": "#1049f1",
        "success-green": "#059669"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "pixel-unit": "4px",
        "gutter": "24px",
        "margin-page": "40px",
        "block-gap": "64px"
      },
      fontFamily: {
        "display-pixel": ["Pixelify Sans", "Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
};
