spring.application.name=aptitudeedge-backend
# Server
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/aptitudeedge_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT
jwt.secret=your_super_secret_key_change_this
jwt.expiration=86400000

